name: loomi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  google_sign_in: ^6.1.0
  cloud_firestore: ^5.6.3
  dio: ^5.8.0+1
  json_serializable: ^6.9.3
  shared_preferences: ^2.5.2
  get_it: ^8.0.3
  flutter_svg: ^2.0.7
  lottie: ^2.3.2
  video_player: ^2.5.1
  chewie: ^1.6.0
  flutter_screenutil: ^5.9.3


  cupertino_icons: ^1.0.8
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^9.1.9


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Epilogue
      fonts:
        - asset: assets/fonts/Epilogue-Light.ttf
          weight: 300
        - asset: assets/fonts/Epilogue-Regular.ttf
          weight: 400
        - asset: assets/fonts/Epilogue-Medium.ttf
          weight: 500
        - asset: assets/fonts/Epilogue-Bold.ttf
          weight: 700
